### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mozmorris** [vjustov/grunt-sinatra#1]
How does this work?

**Comment by vjustov** [comment]
You can run the the `sinatra:serve` task and it will run `rackup` on the root directory by default, serving the page on the 9292 port. You can pass it an options hash with the some of the rackup flags, but this is not thoroughly tested yet. the ruby process is run as a child process and once the grunt exits the ruby process is killed.

**Comment by mozmorris** [comment]
Awesome, thanks.
